name: basic-react-app-CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check-out the code
        uses: actions/checkout@v3

      - name: login to github
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build the image
        run: docker build -t dockerimg  .

      - name: run the image
        run: docker run -e CI=true --name testcontainer  dockerimg npm run test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ vars.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ vars.AWS_SECRET_KEY }}
          application_name: basicreact
          environment_name: basicreact-env
          version_label: ${{ github.sha }}
          region: ap-southeast-2
          deployment_package: deploy.zip